Hi there! I am Nicolas - developer.

This document is a summary of my analysis of https://github.com/ninenines/ranch[Ranch] 2.0.0-rc.1 source code, performed in August 2019.
It has been done purely in an old-school way, cloning the project from github
and going through it manually.

By helping understand the intricacy of a well-established but somewhat small Erlang library,
the reader can:

* improve its Erlang proficiency
* be able to help maintaining Ranch
* be able to reuse Ranch codebase or get inspired by it for other projects

:warning-caption: pass:[<span style="font-size: 4em">&#9888;</span>]
WARNING: This analysis has been performed while I just started learning Erlang,
right after going through https://learnyousomeerlang.com/[Learn You Some Erlang For Great Good].
If you find any errors, a pull-request or a new GitHub issue is welcome! ;)

== Copyright and License

=== __Ranch: what's under the hood?__

Copyright © 2019, Nicolas Gimenez <nicolas.gimenez@baozi.technology>. +
__"Ranch: what's under the hood?"__ is published under the
https://creativecommons.org/licenses/by-sa/3.0/[Creative Commons Attribution-ShareAlike 3.0 Unported License (CC BY-SA 3.0)] +

=== __Ranch__

Ranch is copyrighted by https://github.com/essen[Loïc Hoguin],
which kindly encouraged me to publish this code analysis. +
I am not (yet ;)) a contributor of this project.
I am not related to Nine Nines. +
Click https://salt.bountysource.com/teams/ninenines[here] if you wish to support Ranch.