Hi there! I am Nicolas - developer.

This document is a summary of my analysis of https://github.com/ninenines/ranch[Ranch] 2.0.0-rc.1 source code, performed in August 2019.
It has been done purely in an old-school way, cloning the project from github
and going through it manually.

By helping understand the intricacy of a well-established but somewhat small Erlang library,
the reader can:

* improve its Erlang proficiency
* be able to help maintaining Ranch
* be able to reuse Ranch codebase or get inspired by it for other projects

:warning-caption: pass:[<span style="font-size: 4em">&#9888;</span>]
WARNING: This analysis has been performed while I just started learning Erlang,
right after going through https://learnyousomeerlang.com/[Learn You Some Erlang For Great Good].
If you find any errors, a pull-request or a new GitHub issue is welcome! ;)

== License and disclaimer

This work is distributed under the same license as _Ranch_ itself, https://opensource.org/licenses/ISC[ISC License]. +

Ranch was originally built by https://github.com/essen[Loïc Hoguin],
which kindly encouraged me to publish this code analysis. +
I am not related to Nine Nines. +
https://salt.bountysource.com/teams/ninenines[Donate] if you wish to support Ranch.
